name: Doubacore
description: A bunch of essential tools for a PocketMine server
main: Nouma\Doubacore\Doubacore
api: 5.0.0
version: 0.2.1
author: Nouma

permissions:
  doubacore.command.god:
    default: op
  doubacore.command.god.self:
    default: op
  doubacore.command.god.other:
    default: op

  doubacore.command.heal:
    default: op
  doubacore.command.heal.self:
    default: op
  doubacore.command.heal.other:
    default: op

  doubacore.command.speed:
    default: op
  doubacore.command.speed.self:
    default: op
  doubacore.command.speed.other:
    default: op

  doubacore.command.warp:
    default: op
  doubacore.command.warp.list:
    default: true
  doubacore.command.warp.*:
    default: op
  doubacore.command.setwarp:
    default: op
  doubacore.command.delwarp:
    default: op

  doubacore.command.kit:
    description: Use kit command.
    default: op
  doubacore.command.kit.list:
    description: List available kits.
    default: true
  doubacore.command.kit.*:
    description: Grant access to all available kits.
    default: op

  doubacore.command.home:
    description: Use home command.
    default: true
  doubacore.command.sethome:
    description: Set a home teleportation point.
    default: true
  doubacore.command.delhome:
    description: Delete a home teleportation point.
    default: true
  doubacore.command.home.other:
    description: List and use others homes.
    default: op